update: missing irq-routines
$ make
gcc -m32 -ffreestanding -fno-builtin -nostdlib -nostartfiles -Wall -Wextra -Wno-unused-value -Wno-unused-parameter -c kernel.c -o kernel.o
ld -nostdlib -T kernel.ld -m i386pe -o kernel.coff \
    code32.o isr.o kernel.o util.o
ld: isr.o:isr.asm:(.text+0x112): undefined reference to `fault_handler'
ld: isr.o:isr.asm:(.text+0x1ab): undefined reference to `irq_handler'
ld: kernel.o:kernel.c:(.text+0x60d): undefined reference to `irq0'
ld: kernel.o:kernel.c:(.text+0x632): undefined reference to `irq1'
ld: kernel.o:kernel.c:(.text+0x657): undefined reference to `irq2'
ld: kernel.o:kernel.c:(.text+0x67c): undefined reference to `irq3'
ld: kernel.o:kernel.c:(.text+0x6a1): undefined reference to `irq4'
ld: kernel.o:kernel.c:(.text+0x6c6): undefined reference to `irq5'
ld: kernel.o:kernel.c:(.text+0x6eb): undefined reference to `irq6'
ld: kernel.o:kernel.c:(.text+0x710): undefined reference to `irq7'
ld: kernel.o:kernel.c:(.text+0x735): undefined reference to `irq8'
ld: kernel.o:kernel.c:(.text+0x75a): undefined reference to `irq9'
ld: kernel.o:kernel.c:(.text+0x77f): undefined reference to `irq10'
ld: kernel.o:kernel.c:(.text+0x7a4): undefined reference to `irq11'
ld: kernel.o:kernel.c:(.text+0x7c9): undefined reference to `irq12'
ld: kernel.o:kernel.c:(.text+0x7ee): undefined reference to `irq13'
ld: kernel.o:kernel.c:(.text+0x813): undefined reference to `irq14'
ld: kernel.o:kernel.c:(.text+0x838): undefined reference to `irq15'
make: *** [Makefile:33: kernel.coff] Error 1